name: c19analyse
type: python:3.8

web:
    commands:
        start: python server.py
        #start: gunicorn --bind 0.0.0.0:8888 wsgi:app

hooks:
  build: |
    pip install -r requirements.txt

disk: 512
