name: c19analyse
type: python:3.8

web:
    commands:
        start: python server.py

hooks:
  build: |
    pip install -r requirements.txt


mounts:
    'uploads':
        source: local
        source_path: uploads/


disk: 1024
